import Head from 'next/head'
import Header from '../components/Header'
import Landing from '../components/Landing'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Header />
        <Landing />
      </div>
    </div>
  )
}
